# API endpoints
CHATGPT_LOGIN_URL = "https://chatgpt.com/auth/login?next=%2F"
CHATGPT_SESSION_API = "https://chatgpt.com/api/auth/session"

# API timeouts (seconds)
CPA_MANAGEMENT_TIMEOUT = 30
CLOUDMAIL_API_TIMEOUT = 30

# Timeouts (milliseconds)
PAGE_LOAD_TIMEOUT = 30000
EMAIL_INPUT_TIMEOUT = 30000
CODE_INPUT_TIMEOUT = 60000
LOGIN_SUCCESS_TIMEOUT = 120000

# Retry settings
CODE_FETCH_MAX_RETRIES = 3
CODE_FETCH_RETRY_DELAY = 5
CLOUDMAIL_CODE_FETCH_MAX_RETRIES = 5
CLOUDMAIL_CODE_FETCH_RETRY_DELAY = 3
LOGIN_MAX_RETRIES = 2
LOGIN_RETRY_DELAY = 2

# Browser settings
BROWSER_PROFILE_DIR = "./browser_profile"
OUTPUT_DIR = "./output"
LOG_DIR = "./logs"
DIAGNOSTICS_DIR = "./artifacts"
CLOUDMAIL_CONFIG_PATH = "./cloudmail.config.json"
PROXY = None  # Browser proxy, e.g., "socks5://127.0.0.1:1080"
FLARESOLVERR_URL = "http://127.0.0.1:8191/v1"
FLARESOLVERR_MAX_TIMEOUT = 60000
FLARESOLVERR_WAIT_SECONDS = 5
EMAIL_FORM_STABILIZE_SECONDS = 30
EMAIL_POST_SUBMIT_TIMEOUT_SECONDS = 60
